import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const read = (path) => readFileSync(join(root, path), 'utf8');

test('shared UI primitives exist for dashboard pages', () => {
  for (const file of [
    'src/web/components/ui/page-shell.tsx',
    'src/web/components/ui/card.tsx',
    'src/web/components/ui/status-badge.tsx',
    'src/web/components/ui/empty-state.tsx',
  ]) {
    assert.equal(existsSync(join(root, file)), true, `${file} should exist`);
  }
});

test('global tokens include semantic dashboard states', () => {
  const css = read('src/web/styles.css');
  for (const token of ['--success', '--warning', '--danger', '--info', '--surface-raised', '--text-muted']) {
    assert.match(css, new RegExp(token.replace('--', '--')), `${token} token should exist`);
  }
});

test('OTT home and navigation use the refreshed UI structure', () => {
  const home = read('src/web/pages/home.tsx');
  const nav = read('src/web/components/bottom-nav.tsx');
  const admin = read('src/web/components/admin-token-control.tsx');
  assert.match(home, /오늘 상태/);
  assert.match(home, /위험 알림/);
  assert.match(home, /바로가기/);
  assert.match(home, /파티 재정비 대상/);
  assert.match(home, /완료한 파티 재정비 대상/);
  assert.match(home, /해당 계정으로 또 다시 파티 모집을 진행할건가/);
  assert.match(home, /기존 구독이 유지됐는가/);
  assert.match(home, /구독 결제일은 매달 몇일인가/);
  assert.match(home, /subscriptionBillingDay/);
  assert.match(home, /랜덤 12자리 비밀번호 생성/);
  assert.match(home, /변경 예정 비밀번호/);
  assert.match(home, /PIN 번호를 변경했는가/);
  assert.match(home, /공지 했는가/);
  assert.match(home, /파티 비번 & PIN 알림/);
  assert.match(home, /남은 파티원 공지 템플릿/);
  assert.match(home, /복사/);
  assert.match(home, /전체공지 발송/);
  assert.match(home, /buildPartyNoticeTemplate/);
  assert.match(home, /excludeDealUsids/);
  assert.match(home, /noticeSent/);
  assert.match(home, /변경된 PIN/);
  assert.match(home, /PIN 변경 확인됨/);
  assert.match(home, /이메일 새탭 열기/);
  assert.match(home, /기존 파티원 프로필을 제거했는가/);
  assert.match(home, /구독을 해지했는가/);
  assert.match(home, /파티 재시작 YES 시 완료 탭으로 이동/);
  assert.match(home, /splitPartyMaintenanceChecklistItems\(items\)/);
  assert.match(home, /대상 복귀/);
  assert.match(home, /이용중 0명|7일 이내 만료/);
  assert.match(home, /buildPartyMaintenanceTargets\(data/);
  assert.match(home, /party-maintenance-checklists/);
  const write = read('src/web/pages/write.tsx');
  assert.match(write, /WRITE_PRODUCT_PRESET_KEY/);
  assert.match(write, /글 기본값 프리셋/);
  assert.match(write, /현재 제목·설명 기본값으로 저장/);
  assert.match(write, /기본값 불러오기/);
  assert.match(write, /기본값 초기화/);
  assert.match(write, /loadWriteProductPresets/);
  assert.match(write, /saveCurrentAsPreset/);
  assert.match(write, /applyPresetForService/);
  assert.match(write, /resetPresetForService/);
  assert.match(write, /재정비 DB 자동 불러오기/);
  assert.match(write, /findMaintenanceCredentialForAlias/);
  assert.match(write, /maintenanceCredentialStore/);
  assert.match(write, /setKeepPasswd\(credential\.password\)/);
  assert.match(write, /setKeepPasswd\(''\)/);
  assert.match(write, /랜덤 프로필명/);
  assert.match(write, /profileNickname/);
  assert.match(write, /buildProfileWarningMemo/);
  assert.match(write, /profile-assignments/);
  assert.match(write, /⚠️ 1인 1프로필 원칙 안내/);
  assert.doesNotMatch(home, /최근 만료 파티 체크리스트/);
  assert.doesNotMatch(home, /expired-party-checklists/);
  assert.match(home, /실시간 채팅 알림/);
  assert.match(home, /최신 메시지 10개/);
  assert.doesNotMatch(home, /안 읽은 문의 내용/);
  assert.match(home, /메시지 도착/);
  assert.match(home, /계정/);
  assert.match(home, /내용 확인 필요/);
  assert.match(home, /캐시 표시중/);
  assert.match(home, /rateLimited/);
  assert.match(home, /messageHydrationFailedCount/);
  assert.match(home, /buildLatestChatMessages\(json\.rooms \|\| \[\], 10\)/);
  assert.doesNotMatch(home, /buildUnreadChatAlerts\(json\.rooms \|\| \[\], 5\)/);
  assert.doesNotMatch(home, /buildChatAlerts\(json\.rooms \|\| \[\], 5\)/);
  assert.match(home, /fetch\('\/api\/chat\/rooms'\)/);
  const chat = read('src/web/pages/chat.tsx');
  assert.match(chat, /isMobile/);
  assert.match(chat, /안읽음만 보기/);
  assert.match(chat, /구매자 메시지 최신순/);
  assert.match(chat, /계정별 정리/);
  assert.match(chat, /useState<ChatSortMode>\('latest'\)/);
  assert.match(chat, /읽음 처리/);
  assert.match(chat, /목록/);
  assert.match(chat, /mobileChatHidden/);
  assert.match(home, /buildServiceStats\(data, manuals\)/);
  assert.match(home, /buildMonthlyNetProfitSummary\(data, manuals\)/);
  assert.match(home, /그레이태그 월환산×0\.9 \+ 수동 월환산 - 구독료/);
  assert.match(home, /풀파티시/);
  assert.match(home, /fullPartyNetProfit/);
  assert.match(home, /fullPartyUpside/);
  assert.match(home, /fullPartyNetProfit \/ 10000/);
  assert.doesNotMatch(home, /일단가×30×인원×0\.9 - 구독료/);
  assert.doesNotMatch(home, /FULL_PARTY_NET_EXTRA/);
  assert.match(home, /buildDailyInflow\(data, manuals, \{ days: range \}\)/);
  assert.match(home, /serviceKeys/);
  assert.match(home, /서비스별 누적 막대/);
  assert.match(home, /계정 확인중/);
  assert.match(home, /운영센터/);
  assert.match(home, /프로필 정리 · 수동 고객 · 카카오톡 응대 큐/);
  assert.match(home, /fetch\('\/api\/operations-center\/summary'\)/);
  assert.match(home, /채팅\/초안 확인/);
  assert.match(home, /계정·프로필 정리/);
  const homeManageIndex = home.indexOf('<ManagePage />');
  const homeSafeModeIndex = home.indexOf('{safeMode &&');
  assert.ok(homeManageIndex > -1 && homeSafeModeIndex > -1 && homeManageIndex < homeSafeModeIndex, 'ManagePage should render near the top of Home before status panels');
  const dashboardStats = read('src/web/lib/dashboard-stats.ts');
  assert.match(dashboardStats, /OTT_MONTHLY_SUBSCRIPTION_COST/);
  assert.match(dashboardStats, /GRAYTAG_NET_RATE = 0\.9/);
  assert.match(dashboardStats, /source: 'manual'/);
  assert.match(read('src/lib/account-check-inflow.ts'), /firstSeenDate/);
  assert.match(read('src/lib/account-check-inflow.ts'), /isCancelledOrRemovedDeal/);
  assert.match(nav, /운영/);
  assert.match(nav, /자동화/);
  assert.match(admin, /인증됨|잠김|오류/);
  const manage = read('src/web/pages/manage.tsx');
  assert.match(manage, /<ManualResponseQueuePanel \/>/);
  assert.doesNotMatch(manage, /<ProfileAuditPanel/);
  assert.doesNotMatch(manage, /프로필 수 검증/);
  assert.match(manage, /수동 고객\/카카오톡 응대 큐/);
  assert.match(manage, /operations-center\/manual-response-queue/);
  assert.match(manage, /findExactPasswordForAccount/);
  assert.match(manage, /requireExactAliasMemoForAutoFill/);
  assert.match(manage, /buildAutoFillDeliveryMemo/);
  assert.match(manage, /배정된 프로필 이름/);
  assert.match(manage, /1인 1프로필 안내 3회 반복/);
  assert.match(manage, /fillProfileNickname/);
  assert.match(manage, /generateUniqueProfileNicknames/);
  assert.match(manage, /전체 메꾸기 미리보기 필요/);
  const generatedAccounts = read('src/lib/generated-accounts.ts');
  assert.match(manage, /계정 생성/);
  assert.match(manage, /getGeneratedAccountCreationCopy\(accountCreateService\)/);
  assert.match(manage, /accountCreateCopy\.description/);
  assert.match(manage, /accountCreateCopy\.prefixLabel/);
  assert.match(manage, /accountCreateCopy\.prefixHelp/);
  assert.match(generatedAccounts, /웨이브 19,500원 더블 플랜/);
  assert.match(generatedAccounts, /티빙 로그인 ID는 gtwavveN/);
  assert.match(generatedAccounts, /웨이브 로그인은 같은 prefix의 Email alias/);
  assert.match(generatedAccounts, /더블플랜 번호 \/ 티빙 로그인 ID/);
  assert.match(generatedAccounts, /Email 대시보드 alias/);
  assert.match(generatedAccounts, /티빙\+웨이브/);
  assert.match(generatedAccounts, /더블이용권 묶음 관리/);
  assert.doesNotMatch(manage, /티빙 연결됨/);
  assert.doesNotMatch(manage, /웨이브 연결됨/);
  assert.doesNotMatch(manage, /doublePassBundle/);
  assert.match(manage, /generated-accounts\/create/);
  assert.match(generatedAccounts, /alias prefix 직접 설정/);
  assert.match(manage, /accountCreatePrefix/);
  assert.match(manage, /aliasPrefix: accountCreatePrefix\.trim\(\)/);
  assert.match(manage, /계정 관리에 표시됨/);
  assert.match(generatedAccounts, /비워두면 서비스별 다음 번호를 자동 생성/);
  assert.match(manage, /생성만 완료/);
  assert.match(manage, /결제 완료/);
  assert.match(manage, /findEmailAliasId\(acct\)/);
  assert.match(manage, /확인중 \${serviceVerifyingCount}명/);
  assert.match(manage, /계정 확인중\(파란색 추적\)/);
  assert.match(manage, /isAccountCheckingMember/);
  assert.match(manage, /includes\('계정확인중'\)/);
  assert.match(manage, /'#2563EB'/);
  assert.match(manage, /openEmailDashboardForAccount\(acct\)/);
  assert.match(manage, /이메일 대시보드 새 탭 열기/);
  assert.match(manage, /https:\/\/email-verify\.xyz\/email\/mail/);
  assert.doesNotMatch(manage, /summarizeBuyerCancelledDeals/);
  assert.doesNotMatch(manage, /결제했다 취소한 구매자/);
  assert.match(manage, /생성계정 게시글 작성/);
  assert.match(manage, /\$\{vi\.unfilled\}자리 게시글 작성/);
  assert.match(manage, /관리자 전용 ID · PW · PIN/);
  assert.match(manage, /계정 클릭 시에만 표시/);
  assert.match(manage, /복붙용/);
  assert.match(manage, /PIN 번호 재설정/);
  assert.match(manage, /변경된 핀번호를 다른 사람들에게 전달했나요/);
  assert.match(manage, /Y/);
  assert.match(manage, /N/);
  assert.match(manage, /결제\/가입 완료/);
  assert.match(manage, /paymentStatus === 'paid'/);
  assert.match(manage, /maintenanceChecklistStore/);
  assert.match(manage, /findMaintenanceCredentialForAccount/);
  assert.match(manage, /credential\?\.password/);
  assert.match(manage, /credential\?\.pin/);
  assert.match(manage, /serviceUsingWithManual/);
  assert.match(manage, /totalManualUsingCount/);
  assert.match(manage, /forceRefresh: true/);
  assert.match(manage, /판매 게시물 없이도 계정 관리에 유지/);
  assert.match(manage, /방금 생성한 계정 삭제/);
  assert.match(manage, /method:'DELETE'/);
  assert.match(manage, /handleDeleteGeneratedAccount/);
  assert.match(read('src/api/index.ts'), /app\.delete\('\/generated-accounts\/:id'/);
  assert.match(read('src/api/index.ts'), /createSimpleLoginCustomAlias/);
  assert.doesNotMatch(read('src/api/index.ts'), /graytag-account-generator/);
  assert.match(read('src/api/index.ts'), /nextGeneratedAliasPrefix/);
  assert.match(read('src/api/index.ts'), /excludeDealUsids/);
  assert.match(read('src/api/index.ts'), /noticeSent: true/);
  assert.match(read('src/api/index.ts'), /manualPrefix: aliasPrefix/);
  assert.match(read('src/api/index.ts'), /normalizeManualAliasPrefix/);
  assert.match(read('src/api/index.ts'), /api\/v2\/alias\/custom\/new/);
  assert.match(read('src/api/index.ts'), /DELETE.*api\/aliases/);
  assert.match(read('src/api/index.ts'), /mergeGeneratedAccountsIntoManagement/);
  assert.match(read('src/api/index.ts'), /mergeOnSaleAccountsIntoManagement\(withGeneratedAccounts, onSaleByKeepAcct\)/);
  assert.match(read('src/api/index.ts'), /applyManagementHiddenAccounts/);
  assert.match(read('src/api/index.ts'), /MANAGEMENT_HIDDEN_ACCOUNTS_PATH/);
  assert.match(read('src/api/index.ts'), /managementCache\.clear\('auto-session'\)/);
  assert.doesNotMatch(read('src/api/index.ts'), /mergeTvingWavveServicesForManagement/);
  assert.match(read('src/api/index.ts'), /shouldHydrateDeliveredAccountFromChat/);
  assert.match(read('src/api/index.ts'), /extractDeliveredAccountFromChats/);
  assert.match(read('src/api/index.ts'), /extractGraytagChats\(msgData\)/);
  assert.match(read('src/api/index.ts'), /findBeforeUsingLenderDeals/);
  assert.match(read('src/api/index.ts'), /계정확인중 포함/);
  assert.match(read('src/api/index.ts'), /extractLenderDeals/);
  assert.match(read('src/api/index.ts'), /isAccountCheckingDeal/);
  assert.match(read('src/api/index.ts'), /ACCOUNT_CHECK_INFLOW_PATH/);
  assert.match(read('src/api/index.ts'), /buildAccountCheckInflowStore/);
  assert.match(read('src/api/index.ts'), /accountCheckInflow\.inflowDateByDealUsid/);
  assert.match(chat, /new URLSearchParams\(window\.location\.search\)\.get\('room'\)/);
  assert.doesNotMatch(manage, /ANY product with a password from ANY account/);
});
